/**
 * Codex Setup Helpers
 * Syncs slash command prompts and ensures AGENTS.md router instructions.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, unlinkSync } from 'fs';
import { join } from 'path';
import { prepareForCodex } from './runtime-compat.js';

const ROUTER_START = '<!-- CCASP-CODEX-SLASH-ROUTER:START -->';
const ROUTER_END = '<!-- CCASP-CODEX-SLASH-ROUTER:END -->';

function getRouterBlock() {
  return [
    ROUTER_START,
    '## CCASP Codex Slash Router',
    '',
    'When the user enters a message that starts with `/`, treat it as a CCASP command alias.',
    '',
    'Command handling rules:',
    '1. Parse the first token as the command id (remove leading `/`).',
    '2. Look up `.codex/prompts/<command-id>.md` (preferred) or `.codex/prompts/<command-id>.txt` (legacy fallback).',
    '3. Check the `codex-support:` field in the YAML frontmatter of the prompt file:',
    '   - `codex-support: unsupported` — Respond: "This command requires Claude Code CLI and cannot run in Codex. [reason from prompt file]. To use it, switch to Claude Code CLI and run `/<command-id>`." Then stop — do not attempt execution.',
    '   - `codex-support: partial` — Prepend: "Note: This command has partial Codex support. Some steps may require manual action compared to Claude Code CLI." Then execute using the prompt body.',
    '   - `codex-support: full` (or field absent) — Execute normally with no disclaimer.',
    '4. Treat remaining user text after the command as command arguments/context.',
    '5. If the prompt file does not exist, list available commands from `.codex/prompts/*.md` grouped by codex-support tier (full first, then partial, then unsupported) and ask the user to choose.',
    '',
    'Do not ignore valid `/command` messages. Do not respond with "slash commands are unsupported" when a mapped prompt exists.',
    ROUTER_END
  ].join('\n');
}

/**
 * Ensure AGENTS.md has slash-router block for Codex command routing.
 * @param {string} cwd
 * @returns {{created: boolean, updated: boolean}}
 */
export function ensureCodexSlashRouter(cwd) {
  const agentsPath = join(cwd, 'AGENTS.md');
  const block = getRouterBlock();

  if (!existsSync(agentsPath)) {
    writeFileSync(agentsPath, `# AGENTS\n\n${block}\n`, 'utf8');
    return { created: true, updated: false };
  }

  const current = readFileSync(agentsPath, 'utf8');
  const start = current.indexOf(ROUTER_START);
  const end = current.indexOf(ROUTER_END);

  if (start !== -1 && end !== -1 && end >= start) {
    const before = current.slice(0, start).replace(/\s*$/, '');
    const after = current.slice(end + ROUTER_END.length).replace(/^\s*/, '');
    const merged = [before, block, after].filter(Boolean).join('\n\n');
    if (merged.trim() !== current.trim()) {
      writeFileSync(agentsPath, `${merged.trimEnd()}\n`, 'utf8');
      return { created: false, updated: true };
    }
    return { created: false, updated: false };
  }

  writeFileSync(agentsPath, `${current.trimEnd()}\n\n${block}\n`, 'utf8');
  return { created: false, updated: true };
}

/**
 * Sync `.claude/commands/*.md` into `.codex/prompts/*.md`.
 * @param {string} cwd
 * @returns {{synced: number, skipped: number}}
 */
export function syncCodexPrompts(cwd) {
  const commandsDir = join(cwd, '.claude', 'commands');
  const promptsDir = join(cwd, '.codex', 'prompts');
  if (!existsSync(commandsDir)) {
    return { synced: 0, skipped: 0 };
  }

  mkdirSync(promptsDir, { recursive: true });

  const files = readdirSync(commandsDir).filter((f) => f.endsWith('.md'));
  let synced = 0;
  let skipped = 0;

  for (const file of files) {
    const src = join(commandsDir, file);
    const dst = join(promptsDir, file);
    try {
      const content = readFileSync(src, 'utf8');
      const rewritten = prepareForCodex(content);
      writeFileSync(dst, rewritten, 'utf8');
      synced += 1;
    } catch {
      skipped += 1;
    }
  }

  // Clean up legacy .txt files that were generated by older Python adapter versions.
  // The .md format is now canonical; .txt files cause confusion for the slash router.
  const allPromptFiles = readdirSync(promptsDir);
  for (const fname of allPromptFiles) {
    if (!fname.endsWith('.txt')) continue;
    try {
      unlinkSync(join(promptsDir, fname));
    } catch {
      // Non-fatal: skip files we can't remove (e.g., permissions)
    }
  }

  return { synced, skipped };
}

/**
 * Full Codex setup step for `ccasp init`.
 * @param {string} cwd
 * @returns {{promptsSynced: number, promptsSkipped: number, routerCreated: boolean, routerUpdated: boolean}}
 */
export function setupCodexSupport(cwd) {
  const promptResult = syncCodexPrompts(cwd);
  const routerResult = ensureCodexSlashRouter(cwd);
  return {
    promptsSynced: promptResult.synced,
    promptsSkipped: promptResult.skipped,
    routerCreated: routerResult.created,
    routerUpdated: routerResult.updated
  };
}
